Adds a flag to turn the GPS power rail off entirely on tbeam
meshtastic/firmware pull request #2019
Opened 2022-12-04 07:12 UTC by code8buster

I realized I could probably put the flag into ButtonThread and do away with the GPS #include, but I figure at some point we might want to make use of it in the GPS class.

2022-12-05 00:06 UTC, thebentern commented
I think before we integrate this, we need a specific frame in screen as a display queue that it's happening. Otherwise it could cause confusion if triggered inadvertantly when a user attempts to quickly toggle to other frames on the screen

2022-12-05 08:27 UTC, code8buster commented
Makes sense to have some acknowledgement of it, in the app and the display. Garth also suggested that the position setting might perform the same function. If I get to it, should that be in a separate pull request?

As is, this PR's changes are gated behind a commented line in the tbeam/variant.h file. Someone who knows what they're doing will have to compile their own, rather than it being included in automated builds.

2022-12-06 21:28 UTC, code8buster commented
This is simply for switching during operation, with a new event in the ButtonThread. The function added to sleep.cpp could be reused by the config proto. I believe I would need to change the initializer if the status of the GPS chip was variable on-boot with respect to that config; currently it just assumes the GPS is always powered on after boot.

2022-12-06 22:51 UTC, caveman99 commented
Doing that would cater for both use cases. remote unattended operation and handheld device. When pulling the power line for the chaip it doesn't matter if it is inited or not, we just have to keep record of the state it should be in.

2022-12-14 08:47 UTC, caveman99 requested changes

2022-12-14 08:47 UTC, caveman99 commented on src/gps/GPS.h
> +  private:
Hesitant here to move them out of private, can you somehow do that via friend class? That will expose these routines only where they're needed.

2022-12-14 08:47 UTC, caveman99 commented on variants/tbeam/platformio.ini
> +  ;-DGPS_POWER_TOGGLE ;uncomment this line to allow a double press on the user button to turn off gps entirely.
I think we can uncomment this for the commit. It's a good thing to have and its tbeam only.

2022-12-14 08:47 UTC, caveman99 commented on src/ButtonThread.h
> +        }
can you add a new string/branch at https://github.com/meshtastic/firmware/blob/de6b752db8874270cd1e82a7ed905e0361afc2ba/src/graphics/Screen.cpp#L533 and https://github.com/meshtastic/firmware/blob/de6b752db8874270cd1e82a7ed905e0361afc2ba/src/graphics/Screen.cpp#L471 to indicate that condition visually? 'disabled by button' or the like.

2022-12-16 17:06 UTC, code8buster commented
I think what I've done won't break anything, or change things too drastically. I believe the change in click timing mostly prevents one from accidentally activating the feature while cycling the screen. It can still happen, but you'd have to be clicking right on the ragged edge of the (perceptible) screen update time.

2022-12-16 19:59 UTC, caveman99 approved these changes

2022-12-17 18:46 UTC, garthvh approved these changes
The faster speed seems better on both the tbeam and rak with rotary, rotary still advances the screen (which also happens already) I do think we should still add and enhancement that takes you to the screen that tells you what happened but that is also a separate issue.

2022-12-17 22:32 UTC, merged

2022-12-17 22:33 UTC, caveman99 commented
@garthvh the rotary issue is because when the inputbroker is active it overrides the button long/double press behaviour. ideally we should combine the inpoutbroker and the onebutton.