fix rak4631_epaper PIN_EINK_EN
meshtastic/firmware pull request #2346
Opened 2023-03-11 10:03 UTC by andrekir

`firmware-rak4631_eink` works again on stock RAK4631 + RAK14000 combo reverting 2.0.8 `PIN_EINK_EN` change back to (0 + 2). tested and confirmed by @feh123

fixes #2101 #2241

2023-03-11 10:43 UTC, caveman99 commented
Good it's working again. Can anybody explain WHY? The Power enable is clearly WB_IO2 and every bit of sample code provided by RAK says Eink_Power_En is WB_IO2 which is GPIO 34 (P1.02)

GPIO2 (P0.02) is QSPI_D3 which is part of the SPI Flash interface. When you trace that line from Core through Baseboard to the I/O connector (alternating named LED3 or IO8) it's a Non-Connect on the Epaper Module.

2023-03-11 10:57 UTC, caveman99 commented
After further investigation we have ButtonThread.h userButtonDoublePressed() which sends a network ping AND switches the backlight on T-Echo. On RAK (Eink firmware only) the double click will pull IO2 and thus power to all peripherals if PIN_EINK_EN stays at 34. We should reconsider making the T-Echo send out a netowrk ping when you toggle the backlight.

The real problem is in EinkDisplay2.cpp Linke 173. On minit it switches the perceived backlight pin to LOW disabling the peripheral power for the EINK Firmware on RAK. So my suspicion that this should best be UNdefined on the 4631-EINK is confirmed. The pin is not named very clever since it only controls the backlight. RAK epaper does NOT use backlight at all :-)

2023-03-11 11:05 UTC, caveman99 commented on variants/rak4631_epaper/variant.h
> +#define PIN_EINK_EN (0 + 2) // (0 + 2) Note: this is really just backlight power
I propose to remove that define alltogether. Should still work. 0+2 just points somehwhere random. see my findings in the main comments.

2023-03-11 11:05 UTC, feh123 commented
As I recall and maybe this is obvious but from --noproto output from 2.0.8 onwards there was always a statement about the screen power on. There was no indication that the screen was an eink.

2023-03-11 11:05 UTC, caveman99 requested changes

2023-03-11 11:05 UTC, caveman99 commented on variants/rak4631_epaper/variant.h
> +#define PIN_EINK_EN (0 + 2) // (0 + 2) Note: this is really just backlight power
I propose to remove that define alltogether. Should still work. 0+2 just points somehwhere random. see my findings in the main comments.

2023-03-12 09:38 UTC, andrekir commented
@feh123 can you please confirm if this change works https://github.com/meshtastic/firmware/suites/11504984242/artifacts/594672483

2023-03-12 10:45 UTC, feh123 commented
Hi @andrekir this looks fine too.

2023-03-12 11:06 UTC, andrekir commented
@feh123 thank you

2023-03-12 18:28 UTC, caveman99 approved these changes

2023-03-12 18:29 UTC, merged