Fix LOG_DEBUG messages when no DEBUG_PORT.
meshtastic/firmware pull request #2485
Opened 2023-05-12 08:25 UTC by IhorNehrutsa

Fix messages like
![image](https://github.com/meshtastic/firmware/assets/70886343/e841b4d7-d7e7-4d3d-af53-6e2f2d6eaa9c)
![image](https://github.com/meshtastic/firmware/assets/70886343/c0ae173b-0e87-465d-b68f-f9b329428e19)

2023-05-12 08:52 UTC, caveman99 requested changes

2023-05-12 08:52 UTC, caveman99 commented on src/main.cpp
> +    else {
If you put parentheses here, do it on both legs of the statement :-)

2023-05-12 15:09 UTC, caveman99 approved these changes

2023-05-13 10:32 UTC, thebentern approved these changes

2023-05-13 10:33 UTC, merged