Update MQTT.cpp
meshtastic/firmware pull request #3057
Opened 2024-01-04 21:10 UTC by dstewartgo

In this issue (https://github.com/meshtastic/firmware/issues/3056), it looks like we can't decrypt encrypted packets from MQTT, because the channel index isn't set on the packet unless it is decoded, meaning that "perhapsDecode" will always fail on encrypted packets.

Fix is to just set the channel regardless of the payload, and let perhapsDecode handle things from there.

2024-01-04 21:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/firmware?pullRequest=3057) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/firmware?pullRequest=3057) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/firmware?pullRequest=3057) it.</sub>

2024-01-05 09:47 UTC, andrekir requested changes

2024-01-05 11:45 UTC, dstewartgo commented on src/mqtt/MQTT.cpp
> +                    p->channel = ch.index;
You're right, the bug is in MQTT connect's calculation of the channel hash!  I'll remove this.

2024-01-05 11:47 UTC, closed without merging

2024-01-05 11:47 UTC, dstewartgo commented
Closing this, as it would break decryption -- instead, will address in MQTT connect.