Add delay so GPS and Radio have time to power up
meshtastic/firmware pull request #3334
Opened 2024-03-05 04:28 UTC by lolsborn

- Added the boot-loader HW ID so you can flash from PlatformIO after inital boot loader setup
- Added a delay on boot which seems to have fixed some race-conditions with both the radio and GPS startup.  Canary has a separate power rail that was being brought up in initVariant() and sometimes either the GPS or Radio hardware would not be present after bootup.

2024-03-05 09:09 UTC, caveman99 requested changes

2024-03-05 09:09 UTC, caveman99 commented on src/main.cpp
> +
Please don't check in whitespace changes. i recommend using `trunk fmt` to reformat your changed files.

2024-03-05 09:09 UTC, caveman99 commented on src/main.cpp
> +    // This is required to give the GPS time to start up as this board has a separate power supply
Can you define something more generic? Other boards may benefit from this delay too, and it's tied in with the `PIN_PWR_EN` so you can name it appropriately. (perhaps `PIN_PWR_DELAY_MS`?)

2024-03-07 13:06 UTC, thebentern approved these changes

2024-03-07 13:11 UTC, merged