Fixed node and channel selection for t-deck
meshtastic/firmware pull request #3695
Opened 2024-04-21 17:24 UTC by nbaddorf

To change nodes and channels, press the tab button (use a modifier key) to change nodes. Press it again to toggle to the channel selection. 

(for a tab modifier key for the t-deck checkout my other pull request: https://github.com/meshtastic/firmware/pull/3668)

2024-04-21 20:09 UTC, caveman99 requested changes
not 100% sure about that one. I remember them being there for a reason. Maybe talk to @mverch67 about that PR

2024-04-23 07:39 UTC, mverch67 commented
> not 100% sure about that one. I remember them being there for a reason. Maybe talk to @mverch67 about that PR

Yes, it's ok. These lines were in place to automatically enter the node selection mode when swiping left/right due to a missing tab key. Now that a tab key is simulated on T-Deck these lines can be removed.

2024-04-23 11:25 UTC, nbaddorf commented
Great thanks!

2024-04-23 12:07 UTC, thebentern approved these changes

2024-04-23 12:09 UTC, merged