Draft contributing.md file
meshtastic/firmware pull request #4507
Opened 2024-08-19 17:05 UTC by rcarteraz

In response to a feature request I've created a draft CONTRIBUTING.md file to review. Welcome to feedback 

To close #4503

2024-08-20 00:21 UTC, fifieldt commented
Probably worth informing people about the CLA and how to sign it?

2024-09-02 08:46 UTC, caveman99 requested changes
Rest LGTM

2024-09-02 08:46 UTC, caveman99 commented on CONTRIBUTING.md
> +5. Create a pull request with a clear description, using the provided template, of your changes
Can we add a note about enabling 'maintainer edit access' here? It's really difficult to handle PR's that don't have this enabled.

![grafik](https://github.com/user-attachments/assets/9e1daf15-3c69-4e1e-8c36-56ac17991fbf)

![grafik](https://github.com/user-attachments/assets/f3130b96-e1d7-44ce-8e23-e75e90e68621)

2024-09-02 08:46 UTC, caveman99 commented on CONTRIBUTING.md
> +[Placeholder for coding standards]
This is basically 'run trunk fmt before creating the PR' :-)

2024-09-06 13:12 UTC, caveman99 approved these changes

2024-09-06 13:12 UTC, merged