Honor flip & color for Heltec T114 and T190
meshtastic/firmware pull request #4786
Opened 2024-09-20 05:37 UTC by todd-herbert

Resolves https://github.com/meshtastic/firmware/issues/4655
Tested working on T114, but needs testing on T190

To-do: update `lib_deps` to point at https://github.com/meshtastic/st7789/pull/1 once merged
___

* Honors `display.config.flip_screen` when set by user
* Honors `TFT_MESH` color if defined in variant.h

2024-09-20 11:46 UTC, caveman99 commented on src/graphics/Screen.cpp
> +
#if defined(USE_ST7789) && defined(TFT_MESH)
[...]
#endif

2024-09-20 11:47 UTC, caveman99 requested changes
See inline comments. 

EDIT: did you upstream the lib changes?

2024-09-20 12:05 UTC, thebentern commented
Lib changes were just merged this morning

2024-09-20 13:20 UTC, todd-herbert commented
I think @HarukiToreda is going to give this a test-run on his T190s later today to check for any unexpected weirdness too 🙏

2024-09-20 14:44 UTC, HarukiToreda commented
i tested the flip on the T190, works great

2024-09-20 18:27 UTC, merged

2024-09-22 22:11 UTC, AaronJackson commented
I recall trying a similar change to enable flipping on the Wireless Tracker, which caused it to crash at boot. I think due to the negative display offset for those boards.

https://github.com/meshtastic/firmware/blob/18aac0ba25e0a638fd7cbab4b73c95105892b88e/variants/heltec_wireless_tracker_V1_0/variant.h#L25-L26

In the end I just hard coded and did a build for that specific board to force the flip (I designed my case upside down...)

```diff
-#define TFT_OFFSET_X 26
-#define TFT_OFFSET_Y -1
+#define TFT_OFFSET_X -26
+#define TFT_OFFSET_Y 1
```

and changed the `tft->setRotation(x)` from 3 to 2.

I'm not in a position to test this at the moment unfortunately