Support for M5Stack Core2 ESP32
meshtastic/firmware pull request #5043
Opened 2024-10-13 16:50 UTC by lboue

Adding support for M5Stack Core2 ESP32 because we no longer have an answer in PR #4471.

2024-10-14 09:47 UTC, lboue commented
@thebentern 
The `build-stm32 (wio-e5) / build-stm32` job failed. Could you restart it?

2024-10-14 10:40 UTC, lboue commented
This time 'CI / gather-artifacts (rp2040) (pull_request_target)' is failing. There is an issue with CI.

2024-10-14 19:00 UTC, caveman99 requested changes
Thanks for your contribution. Please see comments inline

2024-10-15 13:03 UTC, lboue commented on src/graphics/Screen.cpp
> +#if defined(M5STACK_CORE2)
Thanks, I'll make it better.

2024-11-07 16:55 UTC, lboue commented
I have ordered a copy of Core2 for testing. I should receive it next week.

2024-11-12 13:49 UTC, lboue commented
I managed to make it work with the following setup:

| LoRa Pin | Core2 GPIO |
|----------|------------|
| SPI_MOSI | 23         |
| SPI_MISO | 38         |
| SPI_CLK  | 18         |
| RST      | 25         |
| CS       | 27         |
| IRQ      | 35         |

2024-11-15 20:30 UTC, lboue commented
If you'd like to try it out:

[M5Core2_LovyanGFX_1.1.16_part1_firmware.factory.bin.txt](https://github.com/user-attachments/files/17781011/M5Core2_LovyanGFX_1.1.16_part1_firmware.factory.bin.txt)

2024-11-15 21:27 UTC, lboue commented
Touchscreen:

Double-clic             Send position
LONG_PRESS > 5s  Shutdown

2025-10-18 08:22 UTC, fifieldt commented
What's the status of this device support and this patch? :)

2026-07-30 16:06 UTC, caveman99 commented
Platform changed for 2.8.0, no response, closing this

2026-07-30 16:06 UTC, closed without merging