Fix incorrect va_start calls
meshtastic/firmware pull request #5076
Opened 2024-10-15 16:24 UTC by jepler

The 2nd argument of va_start must always be the function parameter immediately before the "..." argument. Otherwise, the behavior is undefined.

Reproducer (compile with `gcc -Wvarargs`):
```c
#include <stdarg.h>
#include <stdio.h>

void wrong_va_arg(const char *format, ...) {
    va_list ap;
    const char *newFormat = "whatever";
    (void)format;

    va_start(ap, newFormat);
    vprintf(newFormat, ap);
    va_end(ap);
}
```

godbolt link to reproducer: https://github.com/jepler/meshtastic-firmware

2024-10-15 16:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/firmware?pullRequest=5076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/firmware?pullRequest=5076) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/firmware?pullRequest=5076) it.</sub>

2024-10-15 16:30 UTC, caveman99 requested changes
Thanks for your contribution, but that change defeats the point of the original change. Namely to add an \n to the format string. The original code actually works while your code would just print all logging without a newline. Did you actually test the change or did you just go by the compiler warning?

2024-10-15 16:32 UTC, jepler commented
This does not to my knowledge "fix a bug": I checked gcc arm and gcc x86_64 and both generate the same code. It's likely a modern compiler just ignores the 2nd argument of va_start in favor of the information in the function prototype.

2024-10-15 18:25 UTC, jepler commented
I am changing the second argument of `va_start`, which must be the named argument just before the `...` argument. Since the argmuent to `log_to_serial` remains `newFormat`, the revised, added-newline version of the format string is used when actual formatting is done.
```c
        va_list arg;
        va_start(arg, format);

        log_to_serial(logLevel, newFormat, arg);
        log_to_syslog(logLevel, newFormat, arg);
```

Here's a example that shows that the revised code with `va_start(arg, format)` + `vprintf(newFormat)` works properly. [Godbolt version](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:27,positionColumn:2,positionLineNumber:27,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:'%23include+%3Cstdarg.h%3E%0A%23include+%3Cstdio.h%3E%0A%23include+%3Cstdlib.h%3E%0A%23include+%3Cstring.h%3E%0A%0Aint+printf_with_newline(const+char+*format,+...)+%7B%0A++++//+append+%5Cn+to+format%0A++++size_t+len+%3D+strlen(format)%3B%0A++++char+*newFormat+%3D+new+char%5Blen+%2B+2%5D%3B%0A++++strcpy(newFormat,+format)%3B%0A++++newFormat%5Blen%5D+%3D+!'%5Cn!'%3B%0A++++newFormat%5Blen+%2B+1%5D+%3D+!'%5C0!'%3B%0A%0A++++va_list+arg%3B%0A++++va_start(arg,+format)%3B%0A++++int+r+%3D+vprintf(newFormat,+arg)%3B%0A++++va_end(arg)%3B%0A%0A++++delete+newFormat%3B%0A++++return+r%3B%0A%7D%0A%0Aint+main()+%7B%0A++++printf_with_newline(%22Your+random+number+is+%25d%22,%0A++++++++++++++++++++++++rand()+%25+6)%3B%0A++++printf_with_newline(%22this+appears+on+its+own+line%22)%3B%0A%7D'),l:'5',n:'1',o:'C%2B%2B+source+%231',t:'0')),k:37.4519062609304,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g142,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'0',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+gcc+14.2+(Editor+%231)',t:'0')),k:29.21476040573627,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+17.0.1',editorid:1,fontScale:14,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+gcc+14.2+(Compiler+%231)',t:'0')),k:33.333333333333336,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).
```c++
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int printf_with_newline(const char *format, ...) {
    // append \n to format
    size_t len = strlen(format);
    char *newFormat = new char[len + 2];
    strcpy(newFormat, format);
    newFormat[len] = '\n';
    newFormat[len + 1] = '\0';

    va_list arg;
    va_start(arg, format);            // <-- va_start argument must be the actual function argument 
    int r = vprintf(newFormat, arg);  // <-- argument to vprintf can differ
    va_end(arg);

    delete newFormat;
    return r;
}

int main() {
    printf_with_newline("Your random number is %d",
                        rand() % 6);
    printf_with_newline("this appears on its own line");
}
```

output:
```
Your random number is 1
this appears on its own line
```

2024-10-15 21:03 UTC, caveman99 approved these changes

2024-10-15 21:04 UTC, caveman99 commented
Sorry, i only reviewed that from a mobile device and thought you changed all of the occurances. I tested a few binaries now with the patch and logging is still fine.

2024-10-15 22:15 UTC, merged

2024-10-16 03:03 UTC, jepler commented
Thank you for taking a second look, I appreciate it!