musl compatibility
meshtastic/firmware pull request #5219
Opened 2024-11-01 22:34 UTC by vidplace7

Existing meshtasticd code currently fails to compile with musl.

This PR seeks to resolve compilation errors for musl so that it can be used with [buildroot-meshtastic](https://github.com/vidplace7/buildroot-meshtastic).

Including `#include <sys/types.h>` resolves issues caused by musl not including `uint` and `ulong` type definitions by default.

2024-11-02 11:22 UTC, thebentern commented
Cousin PR merged!

2024-11-02 15:33 UTC, caveman99 requested changes
the git reference to portduino must be updated to commit a7d95ec808ae5154cfb49ef293b330083c8f684d to include the Cousin PR here.

2024-11-02 20:16 UTC, vidplace7 commented
> the git reference to portduino must be updated to commit a7d95ec808ae5154cfb49ef293b330083c8f684d to include the Cousin PR here.

https://github.com/meshtastic/platform-native/pull/5 done :+1:

2024-11-03 13:23 UTC, caveman99 approved these changes

2024-11-03 13:24 UTC, merged