Issue5194 external notification module refactor
meshtastic/firmware pull request #5384
Opened 2024-11-17 16:45 UTC by Blake-Latchford

Centralize ExternalNotificationModule LED handling

This PR attemtps to take a small step towards addressing issue 5194
by de-duplicating LED handling code within ExternalNotificationModule.
I also refactored the color state code around an alpha channel approach.

2024-11-17 16:47 UTC, Blake-Latchford commented
Flashed to my Heltek v3, and I updated the variant locally to drive some unused pins as LEDs. Logging verified that on startup the LED was disabled. I'm currently trying to figure out how to simulate message reception given that I only own one node right now.

2024-12-12 15:51 UTC, caveman99 requested changes

2024-12-12 15:51 UTC, caveman99 commented on protobufs
Please revert the protobuf change, this will generate merge conficts

2024-12-12 15:51 UTC, caveman99 commented on src/modules/ExternalNotificationModule.cpp
> +
You somehow checked in a conflicted file. there are merge marks that will bomb during compilation.

2024-12-23 23:36 UTC, fifieldt commented
Hi @Blake-Latchford , how's this one going? Need any help?

2025-03-03 06:05 UTC, closed without merging