[WIP] Adding XIAO ESP32C6 with BLE support
meshtastic/firmware pull request #5421
Opened 2024-11-22 16:30 UTC by alexbegoon

Related to https://github.com/meshtastic/firmware/pull/4692
The main purpose of this PR is to enhance the ESP32-C6 target by integrating BLE functionality

2024-11-23 15:01 UTC, caveman99 requested changes

2024-11-23 16:36 UTC, alexbegoon commented on protobufs
My bad! :cold_sweat:  I didn't mean to do that. Resetting now.

2024-11-23 16:55 UTC, alexbegoon commented on bin/version_script.py
For some reason, the call to `platformio-custom.py` and the following part:
```python
# General options that are passed to the C and C++ compilers
projenv.Append(
    CCFLAGS=[
        "-DAPP_VERSION=" + verObj["long"],
        "-DAPP_VERSION_SHORT=" + verObj["short"],
        "-DAPP_ENV=" + env.get("PIOENV"),
    ]
)
```
has no effect. 

I tried adding the following lines to the end of `platformio-custom.py`:
```python
env.Append(
   BUILD_FLAGS=[
      "-DAPP_VERSION=" + verObj["long"],
      "-DAPP_VERSION_SHORT=" + verObj["short"],
      "-DAPP_ENV=" + env.get("PIOENV"),
   ]
)
```
but it didn't work either. 

What eventually worked was [adding this line](https://github.com/meshtastic/firmware/pull/5421/files#diff-cb2ce30e87a30bf39576ce855d63f653548f69a4743af973d9eb71b34d3d3222R12) with the `pre` instruction:
```yaml
extra_scripts = pre:bin/version_script.py
```
It seems that ESP-IDF adds its own `CMakeLists.txt` to the root of the project during compilation, which might cause the root `platformio.ini` to become disconnected.

Maybe another pair of eyes can help here. :slightly_smiling_face:

2024-11-24 14:23 UTC, caveman99 commented on bin/version_script.py
No problem, i just hate duplicate code. i am not python savvy but maybe we can 'include' the new file in the existing one, replacing that part?

2024-11-24 14:24 UTC, caveman99 commented on protobufs
Please don't take that as being offensive :-) It's just these files (and the submodule especially) are notorious for generating merge conflicts later on and they're auto-generated anyway.

2024-11-24 14:26 UTC, caveman99 commented
I am testing a few corner cases with this. is it ok to push minor corrections to your branch?

2024-11-24 14:27 UTC, caveman99 approved these changes

2024-11-25 09:48 UTC, alexbegoon commented
> I am testing a few corner cases with this. Especially with the other C6 board (TLora C6) we have. Is it ok to push minor corrections to your branch?

Sure, I am fine with that!

2024-11-25 17:13 UTC, alexbegoon commented on bin/version_script.py
Agree. I'll refactor this. 

Just for the reference I'll leave it here: https://github.com/platformio/platformio-core/issues/4329#issuecomment-1245553192

2024-11-25 17:53 UTC, alexbegoon commented
@caveman99 just FYI, I'm fixing the failed builds for other targets... :shrug:

2024-12-30 19:59 UTC, alexbegoon commented
Hi @caveman99 ,

I think we're good to go now. Could you take a look please?

2025-01-04 11:39 UTC, caveman99 commented on CMakeLists.txt
Can we add a comment here that this is only for BLE support on ESP-IDF5? Presense of this file may lead people to other conclusions :-)

2025-01-04 14:43 UTC, alexbegoon commented on CMakeLists.txt
Added :slightly_smiling_face:

2025-01-05 10:42 UTC, caveman99 commented
Status: it compiles again but i don't see any BLE advertising emitted from my TLora C6. I have Seeed Xiao C6 incoming in about 10 days to counter-check.

Another thing i noticed when working with VSCode on Windows, due to the different file name handling compared to Linux the wrong RTC.h and CCM.h headers are picked up, presumably in ESP-IDF directories. I could remedy this for the RTC.h by prefixing the dir, but the crypto header is not so easy. I hope i can come up with a fix for this.

2025-01-05 20:12 UTC, caveman99 commented
Bluetooth is indeed enabled per info dump. I was scanning with the Android "nRF52 connect" app for any bluetooth signal from the device and wasn't lucky. i'll compare the sdkconfig later when i am back home.

```
"bluetooth": {
    "enabled": true,
    "mode": "FIXED_PIN",
    "fixedPin": 123456
  },
```

2025-01-20 10:38 UTC, caveman99 commented
I have a xiao C6 here now and can confirm it's advertising after boot. shame it doesn't find a radio but that's not important for this use case :-) Now to find out why the Tlora-C6 doesn't advertise.

By the way, there's excessive logspam from the ESP-IDF libs, every time a GPIO toggles it locks. Is there a way to disable that during build?

2025-01-20 19:12 UTC, alexbegoon commented
Hi @caveman99,

Thank you for confirming on your side. We are one step closer.

First of all, take a look at [this new flag](https://github.com/meshtastic/firmware/pull/5421/files#diff-a2be81c494cea5929f8ca266211533599aaaa0f146c9522a549ceb81407655e0R23). If it is applied, then a 2.4GHz antenna must be attached to the module to avoid damaging the RF output. :warning: I added this to improve BLE coverage.

> Shame it doesn't find a radio, but that's not important for this use case :-)

I’m not sure which radio you're talking about, but I can help you with the wiring if needed. I currently use a cheap AliExpress module with an SX1276, but I plan to switch to a Wio SX1262 soon (the PCB is already in development).

> By the way, there's excessive log spam from the ESP-IDF libs; every time a GPIO toggles, it logs. Is there a way to disable that during the build?

Yes, you're right. I fixed it [here](https://github.com/meshtastic/firmware/pull/5421/files#diff-4be82613e414f7d1ce2ed71901a542a1ffc9407da70f96682c30c6084d78ebfbR112). Now, the log level for GPIO is set to WARN.

> Now to find out why the Tlora-C6 doesn't advertise.

Yes, this is interesting one. I'll check if this module have some sort of balun/rf-switch that has to be managed by a gpio pin.

2025-01-22 11:22 UTC, alexbegoon commented
Hi @caveman99 ,

I checked online, and the best I could find is this [schematic](https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/blob/master/schematic/T3-C6_V1.0.pdf). Unfortunately, it seems the RF frontend is grounded there. I don’t have this module to verify, but I’m quite sure the only antenna it has is a sub-ghz antenna. :man_shrugging: 

I don’t believe this module can support a 2.4 ghz connection.

<img src="https://github.com/user-attachments/assets/4461bef9-b1cc-405e-a1a5-5b4f2ae5ff55"  width="500px" />

2025-02-06 02:40 UTC, weekroom commented
@alexbegoon Hello.
I modified part of the code on the basis of your code, so that the Bluetooth and communication of the device can be found normally in the window system. Currently, I can communicate normally when using an Android phone during the test, but when using an Apple phone, the Bluetooth connection with the device cannot be made, so it is suddenly disconnected. May I ask if you also have such a problem? Here is my Android screen interface (f5ec is my esp32c6 device, e958 is my esp32s3 device)

![0f1b00dc3434d07d0f8b4b6a4e4377a](https://github.com/user-attachments/assets/40087de4-fb6c-4aa0-9bbe-0d721c8ce036)

2025-02-06 14:21 UTC, alexbegoon commented
Hello @weekroom ,
That's great that you got it working!
On my end, it's operating just fine with the Android client. I can't confirm the situation with an iPhone. IIRC, from some Discord discussions, this is a common issue with iPhones due to their aggressive/greedy handling of long-lived connections.

2025-02-07 08:19 UTC, weekroom commented
@alexbegoon hello，
      I have modified the code in the NimbleBluetooth.cpp file about interaction with Bluetooth. At present, I can connect and communicate with an Android phone and an Apple phone. I added the device's Bluetooth name to the broadcast packet in the startAdvertising function, which made it easier for the iPhone interface to display the device's Bluetooth name. Without this operation, the app of the iPhone would be unknown. I hope you find my code useful.
[NimbleBluetooth.txt](https://github.com/user-attachments/files/18703407/NimbleBluetooth.txt)

![c75eaf3841efd7a67c7a9454c97041e](https://github.com/user-attachments/assets/d5a29661-9bda-401a-a599-4a2b5bb16b39)
![29acd64ce105f51356b0f1ce8eab8c3](https://github.com/user-attachments/assets/1046083b-69a6-4aa3-a0a5-62e13121165e)

2025-02-10 16:55 UTC, alexbegoon commented
Hi @weekroom ,

I checked the file, but it seems a bit outdated compared to the current master. Could you please apply your BLE-related changes to this branch?

2025-02-11 01:06 UTC, weekroom commented
ble part and the main branch of the code is different, I am afraid I changed the code only support c6, I did not use other devices to test, so I used a shared file instead of merging in your branch, later I re-changed the code, and added macro definition to distinguish

2025-03-05 15:00 UTC, alexbegoon commented
On 2.6.0 the firmware is building but not sending data over BLE. Converting it back to a draft..

2025-03-08 02:45 UTC, JahazielLem commented
Hi @alexbegoon
I'm trying to test this PR for my custom board based on the ESP32C6, but when I try to compile failed with the following error with with CTR lib:
src/mesh/CryptoEngine.h:81:5: error: 'CTRCommon' does not name a type; did you mean 'AESCommon'?
   81 |     CTRCommon *ctr = NULL;
      |     ^~~~~~~~~
      |     AESCommon
*** [.pio/build/seeed-xiao-esp32c6/src/PowerFSM.cpp.o] Error 1
*** [.pio/build/seeed-xiao-esp32c6/src/RedirectablePrint.cpp.o] Error 1

Have you this problem before?
You PR are the unique that does not compile me, the master branch works OK.
Regards

2025-03-08 18:21 UTC, pierreyves258 commented
> Status: it compiles again but i don't see any BLE advertising emitted from my TLora C6. I have Seeed Xiao C6 incoming in about 10 days to counter-check.
> 
> Another thing i noticed when working with VSCode on Windows, due to the different file name handling compared to Linux the wrong RTC.h and CTR.h headers are picked up, presumably in ESP-IDF directories. I did remedy this for the RTC.h by prefixing the dir, but the crypto engine header is not so easy. I hope i can come up with a fix for this.

Same here, on e esp32-c6-devkitc-1 I don't see BLE advertising and I got this message in logs
`ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0x105 (ESP_ERR_NOT_FOUND) at 0x4203490c
file: "src/platform/esp32/BleOta.cpp" line 16
func: static const esp_partition_t* BleOta::findEspOtaAppPartition()
expression: esp_ota_get_partition_description(part, &app_desc)
ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0x102 (ESP_ERR_INVALID_ARG) at 0x42034992
file: "src/platform/esp32/BleOta.cpp" line 30
func: static String BleOta::getOtaAppVersion()
expression: esp_ota_get_partition_description(part, &app_desc)`

2025-03-10 12:40 UTC, alexbegoon commented
Hi @JahazielLem ,

I had just updated to the latest master and tried to build it at  https://github.com/meshtastic/firmware/pull/5421/commits/5336a1d747f1ee3cb6e6b14a1777948493a8d5a8. It worked fine on my end. I have never seen this error before.

<img src="https://github.com/user-attachments/assets/14bfc1ce-42d7-4a4c-99d7-d0f0c1ca2a04" width="300px"/>

2025-03-31 09:23 UTC, caveman99 approved these changes

2025-04-11 11:32 UTC, caveman99 commented
@alexbegoon can you have a look at https://github.com/meshtastic/firmware/pull/6510 ? this will just update the nimBLE stack to 2.x - it seems to have problems with actually showing the pairing pin, the rest works. If that one is in place, we don't have to macro-guard between the different ESP variants any more and can just add the ESP-IDF stuff needed for C6.

2025-04-12 20:29 UTC, alexbegoon commented
@caveman99 I'll check tomorrow. I'm quite positive because I recently updated this branch with https://github.com/h2zero/esp-nimble-cpp/releases/tag/2.0.2, and it works well with the 2nd version.

2025-04-13 08:30 UTC, alexbegoon commented
Hi @caveman99 I think this change will fix the PIN code issue: https://github.com/meshtastic/firmware/pull/6574/files
Could you please check with an ESP device on your end?

2025-04-17 22:18 UTC, caveman99 requested changes

2025-04-17 22:18 UTC, caveman99 commented on src/nimble/NimbleBluetooth.cpp
>      }
i think the return is right here. inject passkey is for user proovided input through a display or keyboard.

2025-04-17 22:30 UTC, vidplace7 commented on variants/tlora_c6/platformio.ini
> +framework = arduino, espidf
```suggestion
```
You should move these changes into the `esp32c6_base` in `arch/esp32/esp32c6.ini` :+1:

2025-04-17 22:45 UTC, vidplace7 requested changes
I've just got platformio nitpicks for ya :sweat_smile:
Please try to move as much as you can from `variants/**/platformio.ini` to `arch/esp32/esp32c6.ini` to make this a bit more maintainable. :heart:

2025-04-17 22:45 UTC, vidplace7 commented on variants/seeed_xiao_esp32c6/platformio.ini
> +
```suggestion
```
Can this be moved to `arch/esp32/esp32c6.ini`?

2025-04-18 15:52 UTC, alexbegoon commented
@caveman99 @vidplace7 I got your comments, I'll address them asap

2025-04-19 10:09 UTC, alexbegoon commented on variants/seeed_xiao_esp32c6/platformio.ini
> +
Yep, moved it.

2025-04-19 10:09 UTC, alexbegoon commented on sdkconfig.defaults
Added some comments.

2025-04-19 10:09 UTC, alexbegoon commented on variants/tlora_c6/platformio.ini
> +framework = arduino, espidf
Done.

2025-04-19 10:10 UTC, alexbegoon commented on src/nimble/NimbleBluetooth.cpp
>      }
Correct. Fixed that part.

2025-04-19 16:56 UTC, caveman99 requested changes

2025-04-19 16:56 UTC, caveman99 commented on arch/esp32/esp32c6.ini
> +  https://github.com/h2zero/esp-nimble-cpp.git#2.2.1
Hate to be a party pooper, but these GIT pulls are very expensive during build time so we replaced them with on-the-fly ZIP files. Please consider using https://github.com/h2zero/esp-nimble-cpp/archive/2.2.1.zip instead

2025-04-19 20:34 UTC, vidplace7 commented on arch/esp32/esp32c6.ini
> +  https://github.com/h2zero/esp-nimble-cpp.git#2.2.1
```suggestion
  # renovate: datasource=github-tags depName=esp-nimble-cpp packageName=h2zero/esp-nimble-cpp
  https://github.com/h2zero/esp-nimble-cpp/archive/2.2.1.zip
```
Here's a complete version of what @caveman99 described :heart: with renovate

2025-04-20 13:00 UTC, alexbegoon commented on arch/esp32/esp32c6.ini
> +  https://github.com/h2zero/esp-nimble-cpp.git#2.2.1
Yep, improved that part. Thank you!

2025-04-27 20:18 UTC, Ope8888 commented
Hello, can someone provide me with a pre-compiled firmware for ESP32C6?
Thanks.

2025-04-29 17:03 UTC, alexbegoon commented
@caveman99 @thebentern I [added support](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) for new and older version of Arduino-NimBLE. This is related to this [commit](https://github.com/meshtastic/firmware/commit/48dc0e014c451fed8b3979d8548a8f328a613301)

Built and BLE work as expected at commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801):
<img  src="https://github.com/user-attachments/assets/e22ecee0-171e-4176-b696-cebb829c5840" width="300px" />


@Ope8888 here is the pre-compiled version for XIAO ESP32C6 at commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801)  ( :warning:  Don't forget to connect external antenna for 2.4ghz):
[firmware.zip](https://github.com/user-attachments/files/19964597/firmware.zip)

2025-04-30 03:56 UTC, Ope8888 commented
> @caveman99 @thebenternJ'ai [ajouté la prise en charge](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) des nouvelles et anciennes versions d'Arduino-NimBLE. Ceci est lié à ce [commit.](https://github.com/meshtastic/firmware/commit/48dc0e014c451fed8b3979d8548a8f328a613301)
> 
> Construit et BLE fonctionne comme prévu lors du commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) : <img alt="" width="300px" src="https://private-user-images.githubusercontent.com/4046572/438887071-e22ecee0-171e-4176-b696-cebb829c5840.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU5ODM1NzYsIm5iZiI6MTc0NTk4MzI3NiwicGF0aCI6Ii80MDQ2NTcyLzQzODg4NzA3MS1lMjJlY2VlMC0xNzFlLTQxNzYtYjY5Ni1jZWJiODI5YzU4NDAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MzBUMDMyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhYTE3ODA4YTQ2MGY5NzhkMTUxM2RjNmM4MDY5OGQ4MTZkNDVkZTBiNTk0OWRiYTY0NzYyY2JiZThmMDFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ONMVmbWBOwZ2TN6i3OjBWd0bTWcQVujTd7PS3hqE9pM">
> 
> @Ope8888voici la version précompilée pour XIAO ESP32C6 au commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) (⚠️ N'oubliez pas de connecter une antenne externe pour 2,4 GHz) : [firmware.zip](https://github.com/user-attachments/files/19964597/firmware.zip)

What flasher do you use?
I can't flash on my Xiao ESP32C6.
Thanks.

2025-05-19 21:46 UTC, renzenicolai commented
@alexbegoon Thank you for putting in this effort, I'd love to see this PR be merged as that would open the door for me to add support for some hardware I have been working on which also uses the ESP32-C6 to run Meshtastic.

2025-05-20 22:06 UTC, Ope8888 commented
> > > @caveman99@thebenternJ'ai [ajouté la prise en charge](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) des nouvelles et anciennes versions d'Arduino-NimBLE. Ceci est lié à ce [commit.](https://github.com/meshtastic/firmware/commit/48dc0e014c451fed8b3979d8548a8f328a613301) 
> > > Construit et BLE fonctionne comme prévu lors du commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) : 
> > > @Ope8888voici la version précompilée pour XIAO ESP32C6 au commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) (<img alt="" width="300px" src="https://private-user-images.githubusercontent.com/4046572/438887071-e22ecee0-171e-4176-b696-cebb829c5840.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU5ODM1NzYsIm5iZiI6MTc0NTk4MzI3NiwicGF0aCI6Ii80MDQ2NTcyLzQzODg4NzA3MS1lMjJlY2VlMC0xNzFlLTQxNzYtYjY5Ni1jZWJiODI5YzU4NDAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MzBUMDMyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhYTE3ODA4YTQ2MGY5NzhkMTUxM2RjNmM4MDY5OGQ4MTZkNDVkZTBiNTk0OWRiYTY0NzYyY2JiZThmMDFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ONMVmbWBOwZ2TN6i3OjBWd0bTWcQVujTd7PS3hqE9pM">[](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801)⚠️N'oubliez pas de connecter une antenne externe pour 2,4 GHz) : [firmware.zip](https://github.com/user-attachments/files/19964597/firmware.zip)
> > 
> > 
> > J'ai réussi avec une de mes puces ;) mais la deuxième refuse, elle se connecte et se déconnecte en boucle. On peut la réinitialiser ? Merci.
> 
> Oui, vous pouvez réinitialiser manuellement. Consultez ce manuel : https://wiki.seeedstudio.com/xiao_esp32c6_getting_started/#reset

Hello, how do you flash? I succeeded in one of the three. I don't understand what my problem is.
The other two connect and disconnect in a loop, and I can't do anything with them, not even the reset.

2025-05-20 22:09 UTC, Ope8888 commented
> > > > @caveman99@thebenternJ'ai [ajouté la prise en charge](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) des nouvelles et anciennes versions d'Arduino-NimBLE. Ceci est lié à ce [commit.](https://github.com/meshtastic/firmware/commit/48dc0e014c451fed8b3979d8548a8f328a613301)
> > > > Construit et BLE fonctionne comme prévu lors du commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) :
> > > > @Ope8888voici la version précompilée pour XIAO ESP32C6 au commit [685c8c1df](https://github.com/meshtastic/firmware/pull/5421/commits/685c8c1df7f72b6238b42d4f9cceda22f64d0801) (<img alt="" width="300px" src="https://private-user-images.githubusercontent.com/4046572/438887071-e22ecee0-171e-4176-b696-cebb829c5840.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDU5ODM1NzYsIm5iZiI6MTc0NTk4MzI3NiwicGF0aCI6Ii80MDQ2NTcyLzQzODg4NzA3MS1lMjJlY2VlMC0xNzFlLTQxNzYtYjY5Ni1jZWJiODI5YzU4NDAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA0MzBUMDMyMTE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2ZhYTE3ODA4YTQ2MGY5NzhkMTUxM2RjNmM4MDY5OGQ4MTZkNDVkZTBiNTk0OWRiYTY0NzYyY2JiZThmMDFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ONMVmbWBOwZ2TN6i3OjBWd0bTWcQVujTd7PS3hqE9pM">⚠️N'oubliez pas de connecter une antenne externe pour 2,4 GHz) : [firmware.zip](https://github.com/user-attachments/files/19964597/firmware.zip)
> > > 
> > > 
> > > J'ai réussi avec une de mes puces ;) mais la deuxième refuse, elle se connecte et se déconnecte en boucle. On peut la réinitialiser ? Merci.
> > 
> > 
> > Oui, vous pouvez réinitialiser manuellement. Consultez ce manuel : https://wiki.seeedstudio.com/xiao_esp32c6_getting_started/#reset
> 
> Hello, how do you flash? I succeeded in one of the three. I don't understand what my problem is. The other two connect and disconnect in a loop, and I can't do anything with them, not even the reset.

Debug: Sync err Error: Invalid head of packet (0x69): Possible serial noise or corruption.
Debug: Error at sync Error: Invalid head of packet (0x69): Possible serial noise or corruption.
Debug: Sync connect attempt 2
Debug: Sync
Debug: Sync err Error: Invalid head of packet (0x61): Possible serial noise or corruption.
Debug: Error at sync Error: Invalid head of packet (0x61): Possible serial noise or corruption.
Debug: Sync connect attempt 3
Debug: Sync
Debug: Sync err Error: Invalid head of packet (0x64): Possible serial noise or corruption.
Debug: Error at sync Error: Invalid head of packet (0x64): Possible serial noise or corruption.
Debug: Sync connect attempt 4

2025-07-09 08:50 UTC, Ope8888 commented
I can't wait for it to be finished :)

2025-07-22 00:42 UTC, vidplace7 commented
@alexbegoon If you rebase we'd be happy to review this 🙏

2025-07-22 17:53 UTC, alexbegoon commented
@vidplace7 I'll take a look later this week.

2025-08-05 20:48 UTC, alexbegoon commented
I'm not sure if having ESP-IDF here is still relevant. I'm going to try building this using only the fork from Jason2866/platform-espressif32.

2025-08-21 14:36 UTC, Kazagumo commented
i have cloned your branch and immediately encountered this error.

*** Import of non-existent variable ''projenv''
File "/Volumes/sensitive/meshtastic/xiao/bin/platformio-custom.py", line 90, in <module>

i'm using macos,PlatformIO Core, version 6.1.18

**update**

thanks for your patch and idea,now i had get bt+webserver working.
i am using this platform,which have full support of mbedtls and wificlientsecure.h
https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
i just copied nimble2.x patch and made it work,except when calling NimBLEDevice::deinit() and it will fail in esp_bt_controller_deinit();(Related : https://github.com/h2zero/NimBLE-Arduino/issues/1008)

if you want patch please download here(you need to edit variants.h for your device)
https://github.com/Kazagumo/meshtastic_firmware/tree/esp32c6

2025-12-01 17:49 UTC, y0cky commented
Hi!
are there any updates or progress regarding the ESP32-C6 BLE support? Or does anyone have a current firmware build for the XIAO ESP32-C6? Unfortunately, I accidentally bought the C6 instead of the C3, and I’m not able to build a working firmware myself. Thanks!

2026-01-31 16:51 UTC, glenrobertson commented
I have a build for XIAO ESP32-C6 and the SX1262 board here. I connected the sx1262's male pins to the esp32c6 underneath. https://github.com/gxlabs/meshtastic-firmware/commit/1e99e941bc20bd93c87e75cc4c171d72296f64fb

If this works for others too I can look into opening a PR

|board|map|messages|
|-|-|-|
|<img src="https://github.com/user-attachments/assets/22347bda-4969-4820-8ce8-b4aa12f61d5f" width="350" />|<img width="350" height="1311" alt="IMG_3461" src="https://github.com/user-attachments/assets/e9ce242d-5f96-438b-a82b-3c9e4326e3e3" />|<img width="350" height="1311" alt="IMG_3460" src="https://github.com/user-attachments/assets/b2e1f524-44ff-48db-99f0-60d5bda1adb6" />|

2026-07-30 16:05 UTC, closed without merging

2026-07-30 16:05 UTC, caveman99 commented
with the move to ESP-IDF 5.x for the 2.8.0 series this board has mainline support now.