Include meshtasticd dependencies
meshtastic/firmware pull request #5699
Opened 2024-12-30 09:09 UTC by rickmark

This includes changes that support two docker dev container issues:

* Support for floating PlatformIO (locking is causing issues with rebuild) to latest
* Inclusion of additional dependencies in the the devcontiner for building native / `meshtasticd`
** libusb
** libi2c

2024-12-30 20:27 UTC, caveman99 requested changes

2024-12-30 20:27 UTC, caveman99 commented on lib/device-ui
Please revert this checkin

2025-01-12 21:41 UTC, vidplace7 commented on lib/device-ui
Fixed this :+1: since @rickmark disappeared. Should be good to merge these changes now, so devcontainers will function again.

2025-01-13 01:25 UTC, fifieldt approved these changes
This seems fine

2025-02-20 00:26 UTC, fifieldt approved these changes

2025-02-20 13:52 UTC, fifieldt commented
Trunk complained thus:

```
devcontainer/Dockerfile:34:1
 34:1  medium  Pin versions in pip. Instead of `pip install <package>` use `pip install                  hadolint/DL3013
               <package>==<version>` or `pip install --requirement <requirements file>`                                 
```

2025-02-27 05:01 UTC, merged